language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
  - 'node'

script:
  - npm run test-coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
